### ISSUE TITLE
About OGB submission

### ISSUE THREAD

**Issue by weihua916** [ytchx1999/PyG-OGB-Tricks#1]
Thanks for your leaderboard submission. Currently, the GAT paper is referenced, but there are many more tricks that you have used to achieve a good performance. To be qualified for the leaderboard, we require writing a specialized technical report that describes your approach. Please submit again once this is ready. 

Thank you!

**Comment by ytchx1999** [comment]
Hi,
I have modified and added reports in README. Is this okay?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ytchx1999/PyG-OGB-Tricks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 凌晨0:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ytchx1999/PyG-OGB-Tricks] About OGB submission (#1)





 
Thanks for your leaderboard submission. Currently, the GAT paper is referenced, but there are many more tricks that you have used to achieve a good performance. To be qualified for the leaderboard, we require writing a specialized technical report that describes your approach. Please submit again once this is ready.
 
Thank you!

**Comment by weihua916** [comment]
Looks good!
